name: Android CI

on:
  push:
    branches: [ "main", "develop" ] # Adjust branches as needed
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' # Or another distribution
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      # Run assembleDebug or assembleRelease depending on needs
      run: ./gradlew :app:assembleDebug --stacktrace

    # Optional: Run unit tests
    - name: Run unit tests
      run: ./gradlew :app:testDebugUnitTest

    # Optional: Upload build artifact (useful for debug builds)
    # - name: Upload Debug APK
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: debug-apk
    #     path: app/build/outputs/apk/debug/app-debug.apk
